### ISSUE TITLE
Mesh Builder

### ISSUE THREAD

**Issue by Soskar1** [Soskar1/Hero-s-Journey-Mythic-Odyssey#32]
Current method of creating meshes is not well optimized.

Firstly, MeshData can store the same vertices
Secondly, collider for MeshData having too much unnecessary vertices. Amount of verticies can be reduced.

From the second problem leads another problem (watch "ghost verteces" issue)

Possible solution:
1. When MeshData **initialized**, we need to initialize Dictionary<Vector3, int> that will store existing verticies + triangles. During face generation, we need to refer to the dictionary and see if the vertices are occupied. After face generation, we will create quad.

In theory, this approach will reduce amount of verticies significantly. Also, we need to figure out how to properly create a collider for the mesh, because "1." approach is not enough. We need to delete some verticies, that will not be necessary for the mesh collider.

**Comment by Maksasj** [comment]
Bruh, a bunch of text, nah this reading
